#include <CASE_Filter_LST_thr_Impl_adapter.h>

Unit hamr_SW_CASE_Filter_LST_thr_Impl_adapter_initialiseArchitecture() {
  hamr_SW_Impl_Instance_FLT_LST_CASE_Filter_LST_CASE_Filter_LST_initialiseArchitecture(SF_LAST);
}

Unit hamr_SW_CASE_Filter_LST_thr_Impl_adapter_initialiseEntryPoint() {
  hamr_SW_Impl_Instance_FLT_LST_CASE_Filter_LST_CASE_Filter_LST_initialiseEntryPoint(SF_LAST);
}

Unit hamr_SW_CASE_Filter_LST_thr_Impl_adapter_computeEntryPoint() {
  hamr_SW_Impl_Instance_FLT_LST_CASE_Filter_LST_CASE_Filter_LST_computeEntryPoint(SF_LAST);
}
