#include <CASE_Monitor_Req_thr_Impl_adapter.h>

Unit hamr_SW_CASE_Monitor_Req_thr_Impl_adapter_initialiseArchitecture() {
  hamr_SW_Impl_Instance_MON_REQ_CASE_Monitor_Req_CASE_Monitor_Req_initialiseArchitecture(SF_LAST);
}

Unit hamr_SW_CASE_Monitor_Req_thr_Impl_adapter_initialiseEntryPoint() {
  hamr_SW_Impl_Instance_MON_REQ_CASE_Monitor_Req_CASE_Monitor_Req_initialiseEntryPoint(SF_LAST);
}

Unit hamr_SW_CASE_Monitor_Req_thr_Impl_adapter_computeEntryPoint() {
  hamr_SW_Impl_Instance_MON_REQ_CASE_Monitor_Req_CASE_Monitor_Req_computeEntryPoint(SF_LAST);
}
