#include <CASE_AttestationGate_thr_Impl_adapter.h>

Unit hamr_SW_CASE_AttestationGate_thr_Impl_adapter_initialiseArchitecture() {
  hamr_SW_Impl_Instance_AM_Gate_CASE_AttestationGate_CASE_AttestationGate_initialiseArchitecture(SF_LAST);
}

Unit hamr_SW_CASE_AttestationGate_thr_Impl_adapter_initialiseEntryPoint() {
  hamr_SW_Impl_Instance_AM_Gate_CASE_AttestationGate_CASE_AttestationGate_initialiseEntryPoint(SF_LAST);
}

Unit hamr_SW_CASE_AttestationGate_thr_Impl_adapter_computeEntryPoint() {
  hamr_SW_Impl_Instance_AM_Gate_CASE_AttestationGate_CASE_AttestationGate_computeEntryPoint(SF_LAST);
}
