#include <RadioDriver_Attestation_thr_Impl_adapter.h>

Unit hamr_SW_RadioDriver_Attestation_thr_Impl_adapter_initialiseArchitecture() {
  hamr_SW_Impl_Instance_RADIO_RadioDriver_Attestation_RadioDriver_Attestation_initialiseArchitecture(SF_LAST);
}

Unit hamr_SW_RadioDriver_Attestation_thr_Impl_adapter_initialiseEntryPoint() {
  hamr_SW_Impl_Instance_RADIO_RadioDriver_Attestation_RadioDriver_Attestation_initialiseEntryPoint(SF_LAST);
}

Unit hamr_SW_RadioDriver_Attestation_thr_Impl_adapter_computeEntryPoint() {
  hamr_SW_Impl_Instance_RADIO_RadioDriver_Attestation_RadioDriver_Attestation_computeEntryPoint(SF_LAST);
}
