#include <WaypointPlanManagerService_thr_Impl_adapter.h>

Unit hamr_SW_WaypointPlanManagerService_thr_Impl_adapter_initialiseArchitecture() {
  hamr_SW_Impl_Instance_WPM_WaypointPlanManagerService_WaypointPlanManagerService_initialiseArchitecture(SF_LAST);
}

Unit hamr_SW_WaypointPlanManagerService_thr_Impl_adapter_initialiseEntryPoint() {
  hamr_SW_Impl_Instance_WPM_WaypointPlanManagerService_WaypointPlanManagerService_initialiseEntryPoint(SF_LAST);
}

Unit hamr_SW_WaypointPlanManagerService_thr_Impl_adapter_computeEntryPoint() {
  hamr_SW_Impl_Instance_WPM_WaypointPlanManagerService_WaypointPlanManagerService_computeEntryPoint(SF_LAST);
}
