#ifndef WAYPOINTPLANMANAGERSERVICE_THR_IMPL_ADAPTER_H
#define WAYPOINTPLANMANAGERSERVICE_THR_IMPL_ADAPTER_H

#include <all.h>

Unit hamr_SW_WaypointPlanManagerService_thr_Impl_adapter_initialiseArchitecture();

Unit hamr_SW_WaypointPlanManagerService_thr_Impl_adapter_initialiseEntryPoint();

Unit hamr_SW_WaypointPlanManagerService_thr_Impl_adapter_computeEntryPoint();

#endif
