#include <FlyZonesDatabase_thr_Impl_adapter.h>

Unit hamr_SW_FlyZonesDatabase_thr_Impl_adapter_initialiseArchitecture() {
  hamr_SW_Impl_Instance_FlyZones_FlyZonesDatabase_FlyZonesDatabase_initialiseArchitecture(SF_LAST);
}

Unit hamr_SW_FlyZonesDatabase_thr_Impl_adapter_initialiseEntryPoint() {
  hamr_SW_Impl_Instance_FlyZones_FlyZonesDatabase_FlyZonesDatabase_initialiseEntryPoint(SF_LAST);
}

Unit hamr_SW_FlyZonesDatabase_thr_Impl_adapter_computeEntryPoint() {
  hamr_SW_Impl_Instance_FlyZones_FlyZonesDatabase_FlyZonesDatabase_computeEntryPoint(SF_LAST);
}
