#ifndef SIREUM_GEN_H
#define SIREUM_GEN_H

#include <misc.h>
#include <type-art_ArchitectureDescription.h>
#include <type-art_Art.h>
#include <type-art_Bridge.h>
#include <type-art_Bridge_EntryPoints.h>
#include <type-art_Bridge_Ports.h>
#include <type-art_Connection.h>
#include <type-art_DataContent.h>
#include <type-art_DispatchPropertyProtocol.h>
#include <type-art_DispatchPropertyProtocol_Periodic.h>
#include <type-art_DispatchPropertyProtocol_Sporadic.h>
#include <type-art_Empty.h>
#include <type-art_PortMode_Type.h>
#include <type-art_UConnection.h>
#include <type-art_UPort.h>
#include <type-art_art_Port_45E54D.h>
#include <type-art_art_Port_9CBF18.h>
#include <type-hamr_Arch.h>
#include <type-hamr_ArtNix.h>
#include <type-hamr_Base_Types.h>
#include <type-hamr_Base_Types_Bits_Payload.h>
#include <type-hamr_Drivers_UARTDriver_Impl_Bridge.h>
#include <type-hamr_Drivers_UARTDriver_Impl_Bridge_Api.h>
#include <type-hamr_Drivers_UARTDriver_Impl_Bridge_EntryPoints.h>
#include <type-hamr_Drivers_UARTDriver_Impl_Impl.h>
#include <type-hamr_IPCPorts.h>
#include <type-hamr_Main.h>
#include <type-hamr_PlatformNix.h>
#include <type-hamr_Process.h>
#include <type-hamr_SW_CASE_AttestationGate_thr_Impl_Bridge.h>
#include <type-hamr_SW_CASE_AttestationGate_thr_Impl_Bridge_Api.h>
#include <type-hamr_SW_CASE_AttestationGate_thr_Impl_Bridge_EntryPoints.h>
#include <type-hamr_SW_CASE_AttestationGate_thr_Impl_Impl.h>
#include <type-hamr_SW_CASE_AttestationManager_thr_Impl_Bridge.h>
#include <type-hamr_SW_CASE_AttestationManager_thr_Impl_Bridge_Api.h>
#include <type-hamr_SW_CASE_AttestationManager_thr_Impl_Bridge_EntryPoints.h>
#include <type-hamr_SW_CASE_AttestationManager_thr_Impl_Impl.h>
#include <type-hamr_SW_CASE_Filter_AReq_thr_Impl_Bridge.h>
#include <type-hamr_SW_CASE_Filter_AReq_thr_Impl_Bridge_Api.h>
#include <type-hamr_SW_CASE_Filter_AReq_thr_Impl_Bridge_EntryPoints.h>
#include <type-hamr_SW_CASE_Filter_AReq_thr_Impl_Impl.h>
#include <type-hamr_SW_CASE_Filter_ARes_thr_Impl_Bridge.h>
#include <type-hamr_SW_CASE_Filter_ARes_thr_Impl_Bridge_Api.h>
#include <type-hamr_SW_CASE_Filter_ARes_thr_Impl_Bridge_EntryPoints.h>
#include <type-hamr_SW_CASE_Filter_ARes_thr_Impl_Impl.h>
#include <type-hamr_SW_CASE_Filter_LST_thr_Impl_Bridge.h>
#include <type-hamr_SW_CASE_Filter_LST_thr_Impl_Bridge_Api.h>
#include <type-hamr_SW_CASE_Filter_LST_thr_Impl_Bridge_EntryPoints.h>
#include <type-hamr_SW_CASE_Filter_LST_thr_Impl_Impl.h>
#include <type-hamr_SW_CASE_Filter_OR_thr_Impl_Bridge.h>
#include <type-hamr_SW_CASE_Filter_OR_thr_Impl_Bridge_Api.h>
#include <type-hamr_SW_CASE_Filter_OR_thr_Impl_Bridge_EntryPoints.h>
#include <type-hamr_SW_CASE_Filter_OR_thr_Impl_Impl.h>
#include <type-hamr_SW_CASE_Monitor_Geo_thr_Impl_Bridge.h>
#include <type-hamr_SW_CASE_Monitor_Geo_thr_Impl_Bridge_Api.h>
#include <type-hamr_SW_CASE_Monitor_Geo_thr_Impl_Bridge_EntryPoints.h>
#include <type-hamr_SW_CASE_Monitor_Geo_thr_Impl_Impl.h>
#include <type-hamr_SW_CASE_Monitor_Req_thr_Impl_Bridge.h>
#include <type-hamr_SW_CASE_Monitor_Req_thr_Impl_Bridge_Api.h>
#include <type-hamr_SW_CASE_Monitor_Req_thr_Impl_Bridge_EntryPoints.h>
#include <type-hamr_SW_CASE_Monitor_Req_thr_Impl_Impl.h>
#include <type-hamr_SW_FlyZonesDatabase_thr_Impl_Bridge.h>
#include <type-hamr_SW_FlyZonesDatabase_thr_Impl_Bridge_Api.h>
#include <type-hamr_SW_FlyZonesDatabase_thr_Impl_Bridge_EntryPoints.h>
#include <type-hamr_SW_FlyZonesDatabase_thr_Impl_Impl.h>
#include <type-hamr_SW_RadioDriver_Attestation_thr_Impl_Bridge.h>
#include <type-hamr_SW_RadioDriver_Attestation_thr_Impl_Bridge_Api.h>
#include <type-hamr_SW_RadioDriver_Attestation_thr_Impl_Bridge_EntryPoints.h>
#include <type-hamr_SW_RadioDriver_Attestation_thr_Impl_Impl.h>
#include <type-hamr_SW_UxAS_thr_Impl_Bridge.h>
#include <type-hamr_SW_UxAS_thr_Impl_Bridge_Api.h>
#include <type-hamr_SW_UxAS_thr_Impl_Bridge_EntryPoints.h>
#include <type-hamr_SW_UxAS_thr_Impl_Impl.h>
#include <type-hamr_SW_WaypointPlanManagerService_thr_Impl_Bridge.h>
#include <type-hamr_SW_WaypointPlanManagerService_thr_Impl_Bridge_Api.h>
#include <type-hamr_SW_WaypointPlanManagerService_thr_Impl_Bridge_EntryPoints.h>
#include <type-hamr_SW_WaypointPlanManagerService_thr_Impl_Impl.h>
#include <type-hamr_SW_Impl_Instance_AM_CASE_AttestationManager_App.h>
#include <type-hamr_SW_Impl_Instance_AM_Gate_CASE_AttestationGate_App.h>
#include <type-hamr_SW_Impl_Instance_FC_UART_UARTDriver_App.h>
#include <type-hamr_SW_Impl_Instance_FLT_AReq_CASE_Filter_AReq_App.h>
#include <type-hamr_SW_Impl_Instance_FLT_ARes_CASE_Filter_ARes_App.h>
#include <type-hamr_SW_Impl_Instance_FLT_LST_CASE_Filter_LST_App.h>
#include <type-hamr_SW_Impl_Instance_FLT_OR_CASE_Filter_OR_App.h>
#include <type-hamr_SW_Impl_Instance_FlyZones_FlyZonesDatabase_App.h>
#include <type-hamr_SW_Impl_Instance_MON_GEO_CASE_Monitor_Geo_App.h>
#include <type-hamr_SW_Impl_Instance_MON_REQ_CASE_Monitor_Req_App.h>
#include <type-hamr_SW_Impl_Instance_RADIO_RadioDriver_Attestation_App.h>
#include <type-hamr_SW_Impl_Instance_UXAS_UxAS_App.h>
#include <type-hamr_SW_Impl_Instance_WPM_WaypointPlanManagerService_App.h>
#include <type-hamr_SharedMemory.h>
#include <type-org_sireum_IS_08117A.h>
#include <type-org_sireum_IS_820232.h>
#include <type-org_sireum_IS_82ABD8.h>
#include <type-org_sireum_IS_948B60.h>
#include <type-org_sireum_IS_AA0F82.h>
#include <type-org_sireum_IS_C4F575.h>
#include <type-org_sireum_MNone_2A2E1D.h>
#include <type-org_sireum_MOption_EA1D29.h>
#include <type-org_sireum_MS_2590FE.h>
#include <type-org_sireum_MS_852149.h>
#include <type-org_sireum_MS_94FFA9.h>
#include <type-org_sireum_MS_B5E3E6.h>
#include <type-org_sireum_MS_E444B2.h>
#include <type-org_sireum_MS_F55A18.h>
#include <type-org_sireum_MSome_D3D128.h>
#include <type-org_sireum_None.h>
#include <type-org_sireum_None_3026C5.h>
#include <type-org_sireum_None_39BC5F.h>
#include <type-org_sireum_None_5C1355.h>
#include <type-org_sireum_None_76463B.h>
#include <type-org_sireum_None_93AA2B.h>
#include <type-org_sireum_None_964667.h>
#include <type-org_sireum_None_ED72E1.h>
#include <type-org_sireum_Nothing.h>
#include <type-org_sireum_Option_02FA6D.h>
#include <type-org_sireum_Option_30119F.h>
#include <type-org_sireum_Option_6239DB.h>
#include <type-org_sireum_Option_882048.h>
#include <type-org_sireum_Option_8E9F45.h>
#include <type-org_sireum_Option_9AF35E.h>
#include <type-org_sireum_Option_C622DB.h>
#include <type-org_sireum_Some.h>
#include <type-org_sireum_Some_3E197E.h>
#include <type-org_sireum_Some_4782C6.h>
#include <type-org_sireum_Some_488F47.h>
#include <type-org_sireum_Some_8D03B1.h>
#include <type-org_sireum_Some_D29615.h>
#include <type-org_sireum_Some_E9D1E5.h>
#include <type-org_sireum_Tuple2_D0E3BB.h>
#include <type-org_sireum_Tuple2_EC3B57.h>
#include <type-org_sireum_U8.h>

#if defined(static_assert)
#define STATIC_ASSERT static_assert
#define GLOBAL_STATIC_ASSERT(a, b, c) static_assert(b, c)
#else
#define STATIC_ASSERT(pred, explanation); {char assert[1/(pred)];(void)assert;}
#define GLOBAL_STATIC_ASSERT(unique, pred, explanation); namespace ASSERTION {char unique[1/(pred)];}
#endif

size_t sizeOf(Type t);
void Type_assign(void *dest, void *src, size_t destSize);

#endif